"""Binary outcomes: the linear probability model, logit and probit side by side."""

from __future__ import annotations

from typing import Any

from scipy import optimize, stats

from .._kit import (
    AnimationStep, Domain, EvidenceType, LabBase, LabResult, LabState, P, animation,
    build_frames, context, fmt, int_slider, make_spec, np, pct, ref, scenario,
    seed_control, select, slider, toggle,
)
from ...backends import linear as LM
from ...simulation.random import rng

__all__ = ["LAB", "SPEC", "fit_binary"]

LINKS = ("logit", "probit")


def fit_binary(y, X, link: str = "logit"):
    """Maximum-likelihood fit of a binary-choice model (Newton with a ridge guard)."""
    y = np.asarray(y, dtype=float)
    X = np.asarray(X, dtype=float)
    k = X.shape[1]

    def neg_loglik(b):
        idx = np.clip(X @ b, -35, 35)
        pr = (1 / (1 + np.exp(-idx)) if link == "logit" else stats.norm.cdf(idx))
        pr = np.clip(pr, 1e-10, 1 - 1e-10)
        return -float(np.sum(y * np.log(pr) + (1 - y) * np.log(1 - pr)))

    start = np.zeros(k)
    res = optimize.minimize(neg_loglik, start, method="BFGS")
    b = res.x
    idx = np.clip(X @ b, -35, 35)
    if link == "logit":
        pr = 1 / (1 + np.exp(-idx))
        w = pr * (1 - pr)
    else:
        pr = np.clip(stats.norm.cdf(idx), 1e-10, 1 - 1e-10)
        dens = stats.norm.pdf(idx)
        w = dens**2 / (pr * (1 - pr))
    info = X.T @ (X * w[:, None])
    cov = np.linalg.pinv(info)
    se = np.sqrt(np.clip(np.diag(cov), 0, None))
    marginal = (w if link == "logit" else stats.norm.pdf(idx))
    return {
        "beta": b, "se": se, "cov": cov, "prob": pr, "loglik": -res.fun,
        "converged": bool(res.success),
        "ame": float(np.mean(marginal) ) * b,  # average marginal effects
        "link": link,
    }


SPEC = make_spec(
    "econometrics.logit_probit",
    Domain.ECONOMETRICS,
    "limited_dependent_variables",
    module=__name__,
    levels=("intermediate", "advanced", "phd"),
    modes=("learn", "visualize", "animate", "experiment", "compare", "derive",
           "simulate", "diagnose", "code", "quiz", "references"),
    evidence=EvidenceType.NUMERICAL_DEMONSTRATION,
    controls=(
        slider("beta1", 1.2, -5.0, 5.0, 0.05, group="dgp"),
        slider("beta0", -0.3, -5.0, 5.0, 0.05, group="dgp"),
        int_slider("n", 500, 20, 20000, 10, group="dgp"),
        select("true_link", "logit", ("logit", "probit"), group="dgp"),
        slider("x_spread", 1.0, 0.2, 5.0, 0.05, group="dgp"),
        slider("base_rate", 0.5, 0.01, 0.99, 0.01, group="dgp"),
        int_slider("reps", 400, 50, 4000, 50, group="simulation", expensive=True),
        toggle("show_marginal_effects", True, group="views"),
        toggle("show_lpm_problem", True, group="views"),
        toggle("show_sampling", True, group="views"),
        seed_control(),
    ),
    scenarios=(
        scenario("canonical", "canonical", beta1=1.2, n=500),
        scenario("no_effect", "null", beta1=0.0),
        scenario("strong_effect", "strong", beta1=3.0),
        scenario("weak_effect", "weak", beta1=0.2),
        scenario("rare_outcome", "boundary", base_rate=0.03, n=1000),
        scenario("balanced", "canonical", base_rate=0.5),
        scenario("lpm_out_of_range", "counterexample", beta1=3.0, x_spread=2.5, n=500),
        scenario("small_sample", "small_sample", n=40),
        scenario("large_sample", "large_sample", n=10000),
        scenario("probit_truth", "compare_methods", true_link="probit", beta1=1.0),
        scenario("perfect_separation", "boundary", beta1=5.0, n=40, x_spread=3.0),
    ),
    prerequisites=("regression.simple_linear", "inference.mle"),
    related=("ml.classification_threshold", "inference.mle"),
    tags=("logit", "probit", "lpm", "marginal effects", "odds ratio", "binary choice"),
    aliases=("binary choice", "logit probit", "الاختيار الثنائي", "logistic regression",
             "marginal effects"),
    backends=("scipy", "statsmodels"),
    references=(
        ref("Wooldridge, J. M. (2010). Econometric Analysis of Cross Section and Panel "
            "Data.", kind="book"),
        ref("Cameron, A. C. and Trivedi, P. K. (2005). Microeconometrics.", kind="book"),
    ),
    curriculum_tags=("dz.econometrics2", "ksu.econ541"),
)


class BinaryChoiceLab(LabBase):
    def compute(self, p: dict[str, Any], state: LabState) -> LabResult:
        ctx = context(state)
        res = LabResult()
        n = int(p["n"])
        x, y = self._generate(p, n, state.seed)
        X = np.column_stack([np.ones(n), x])

        lpm = LM.ols(y, X, names=("const", "x"), cov_type="HC1")
        logit = fit_binary(y, X, "logit")
        probit = fit_binary(y, X, "probit")

        res.dgp = ctx.t(
            "labs.bin.dgp",
            "Binary outcome generated by a {link} link with index {b0} + {b1} x; "
            "n = {n}, base rate {r}.",
            link=str(p["true_link"]), b0=fmt(p["beta0"], 2), b1=fmt(p["beta1"], 2),
            n=n, r=pct(float(np.mean(y))),
        )

        res.add_panel(ctx.panel(
            "curves", self._curve_figure(ctx, x, y, lpm, logit, probit, p),
            "labs.bin.figure.curves", evidence=EvidenceType.NUMERICAL_DEMONSTRATION,
        ))
        if p["show_marginal_effects"]:
            res.add_panel(ctx.panel(
                "marginal", self._marginal_figure(ctx, x, logit, probit, lpm),
                "labs.bin.figure.marginal", tab="compare",
                evidence=EvidenceType.NUMERICAL_DEMONSTRATION,
            ))
        if p["show_lpm_problem"]:
            res.add_panel(ctx.panel(
                "lpm", self._lpm_figure(ctx, x, lpm),
                "labs.bin.figure.lpm", tab="diagnostics",
                evidence=EvidenceType.COUNTEREXAMPLE,
            ))
        if p["show_sampling"]:
            sim = self._sampling(p, n, state.seed, int(p["reps"]))
            res.add_panel(ctx.panel(
                "sampling", self._sampling_figure(ctx, sim),
                "labs.bin.figure.sampling", tab="simulation",
                evidence=EvidenceType.SIMULATION,
            ))
            res.metric("ame_agreement",
                       ctx.t("labs.bin.metric.agreement",
                             "Median |AME(logit) - AME(LPM)| across studies"),
                       float(np.median(np.abs(sim["ame_logit"] - sim["lpm"]))))

        base = float(np.mean(y))
        res.metric("base_rate", ctx.t("labs.bin.metric.base", "Share of ones in the data"),
                   base)
        res.metric("lpm_slope", ctx.t("labs.bin.metric.lpm", "LPM slope"),
                   lpm.coef("x"))
        res.metric("logit_coefficient", ctx.t("labs.bin.metric.logit_b",
                                              "Logit index coefficient"),
                   float(logit["beta"][1]))
        res.metric("probit_coefficient", ctx.t("labs.bin.metric.probit_b",
                                               "Probit index coefficient"),
                   float(probit["beta"][1]))
        res.metric("coefficient_ratio", ctx.t("labs.bin.metric.ratio",
                                              "Logit divided by probit coefficient"),
                   float(logit["beta"][1] / max(abs(probit["beta"][1]), 1e-9))
                   * np.sign(probit["beta"][1]),
                   reference=1.6,
                   note=ctx.t("labs.bin.metric.ratio_note",
                              "close to 1.6 because the two links differ mainly by a "
                              "scale factor, not by substance"))
        res.metric("ame_logit", ctx.t("labs.bin.metric.ame_logit",
                                      "Logit average marginal effect"),
                   float(logit["ame"][1]), reference=lpm.coef("x"))
        res.metric("ame_probit", ctx.t("labs.bin.metric.ame_probit",
                                       "Probit average marginal effect"),
                   float(probit["ame"][1]), reference=lpm.coef("x"))
        res.metric("odds_ratio", ctx.t("labs.bin.metric.odds",
                                       "Odds ratio for a one-unit increase in x"),
                   float(np.exp(logit["beta"][1])),
                   note=ctx.t("labs.bin.metric.odds_note",
                              "an odds ratio is not a risk ratio and not a probability "
                              "difference"))
        out_of_range = int(np.sum((lpm.fitted_values < 0) | (lpm.fitted_values > 1)))
        res.metric("lpm_out_of_range", ctx.t("labs.bin.metric.out_of_range",
                                             "LPM predictions outside [0, 1]"),
                   out_of_range,
                   note=ctx.t("labs.bin.metric.out_note",
                              "out of {n} observations", n=n))
        res.metric("logit_loglik", ctx.t("labs.bin.metric.loglik", "Logit log-likelihood"),
                   logit["loglik"])
        res.metric("pseudo_r2", ctx.t("labs.bin.metric.pseudo",
                                      "McFadden pseudo R-squared"),
                   self._pseudo_r2(y, logit["loglik"]),
                   note=ctx.t("labs.bin.metric.pseudo_note",
                              "not comparable with a linear-model R-squared"))

        separated = not logit["converged"] or abs(float(logit["beta"][1])) > 25
        res.assume("correct_link", ctx.t("labs.bin.assume.link_label",
                                         "The link function is correctly specified"), True,
                   detail=ctx.t("labs.bin.assume.link",
                                "Logit and probit differ mainly in tail thickness. With a "
                                "moderate base rate they are practically indistinguishable; "
                                "with rare events they are not."))
        res.assume("no_separation", ctx.t("labs.bin.assume.separation_label",
                                          "No perfect separation"), not separated,
                   detail=ctx.t("labs.bin.assume.separation",
                                "If a regressor perfectly predicts the outcome, the "
                                "likelihood has no interior maximum and the coefficient "
                                "diverges."),
                   consequence="" if not separated else ctx.t(
                       "labs.bin.assume.separation_consequence",
                       "The reported coefficient and its standard error are then "
                       "meaningless numbers produced by a stopped optimizer."))
        res.assume("homoskedasticity", ctx.t("assumptions.homoskedasticity"), False,
                   detail=ctx.t("labs.bin.assume.lpm_hetero",
                                "The LPM error variance is p(x)(1 - p(x)) and therefore "
                                "always heteroskedastic. Robust standard errors are "
                                "mandatory, not optional."))

        res.animations.append(self._animation(ctx, p, n, state.seed))

        res.explain("overview", ctx.t("tabs.overview"),
                    ctx.t("concepts.econometrics.logit_probit.summary"))
        res.explain("intuition", ctx.t("tabs.intuition"),
                    ctx.t("concepts.econometrics.logit_probit.intuition"))
        if ctx.show_math():
            res.explain("math", ctx.t("tabs.math"),
                        ctx.t("concepts.econometrics.logit_probit.math"), kind="math")
        res.explain("misconceptions", ctx.t("tabs.misconceptions"),
                    ctx.t("concepts.econometrics.logit_probit.misconceptions"),
                    kind="misconception")
        res.explain("warning", ctx.t("tabs.warning"),
                    ctx.t("concepts.econometrics.logit_probit.warning"), kind="warning")

        if out_of_range:
            res.warnings.append(ctx.t(
                "labs.bin.warn.range",
                "{k} of {n} linear-probability predictions fall outside [0, 1]. The slope "
                "may still be a reasonable average marginal effect, but the predictions "
                "themselves are not probabilities.",
                k=out_of_range, n=n,
            ))
        if separated:
            res.warnings.append(ctx.t(
                "labs.bin.warn.separation",
                "The maximum-likelihood estimate is diverging - this looks like perfect or "
                "near-perfect separation. Penalized likelihood or an exact method is needed "
                "here; the numbers shown are an artefact of stopping the optimizer.",
            ))
        return res

    @staticmethod
    def _generate(p, n, seed):
        gen = rng(seed, "binary")
        x = gen.normal(0.0, float(p["x_spread"]), n)
        shift = float(stats.norm.ppf(np.clip(float(p["base_rate"]), 0.001, 0.999)))
        index = float(p["beta0"]) + float(p["beta1"]) * x + shift
        if str(p["true_link"]) == "logit":
            prob = 1 / (1 + np.exp(-np.clip(index, -35, 35)))
        else:
            prob = stats.norm.cdf(index)
        return x, (gen.random(n) < prob).astype(float)

    @staticmethod
    def _pseudo_r2(y, loglik):
        base = float(np.mean(y))
        ll0 = float(y.size * (base * np.log(max(base, 1e-12))
                              + (1 - base) * np.log(max(1 - base, 1e-12))))
        return 1.0 - loglik / ll0 if abs(ll0) > 1e-12 else float("nan")

    def _sampling(self, p, n, seed, reps):
        reps = min(reps, 1500)
        out = {"lpm": [], "ame_logit": [], "ame_probit": []}
        for r in range(reps):
            x, y = self._generate(p, n, int(seed) * 6700417 + r)
            X = np.column_stack([np.ones(n), x])
            out["lpm"].append(LM.ols(y, X, names=("const", "x")).coef("x"))
            try:
                out["ame_logit"].append(float(fit_binary(y, X, "logit")["ame"][1]))
                out["ame_probit"].append(float(fit_binary(y, X, "probit")["ame"][1]))
            except Exception:  # noqa: BLE001
                out["ame_logit"].append(np.nan)
                out["ame_probit"].append(np.nan)
        return {k: np.asarray(v) for k, v in out.items()}

    def _curve_figure(self, ctx, x, y, lpm, logit, probit, p):
        grid = np.linspace(float(x.min()) - 0.5, float(x.max()) + 0.5, 400)
        G = np.column_stack([np.ones(grid.size), grid])
        fig = ctx.figure(
            "labs.bin.figure.curves",
            xaxis_title=ctx.t("labs.common.axis.x"),
            yaxis_title=ctx.t("labs.bin.axis.probability", "P(y = 1 | x)"),
            height=440,
        )
        gen = rng(1, "jit")
        P.add_points(fig, x, y + gen.normal(0, 0.02, y.size),
                     ctx.t("labs.bin.trace.observations", "observations (jittered)"),
                     "muted", theme=ctx.theme, size=5, opacity=0.35)
        P.add_curve(fig, grid, G @ lpm.coefficients,
                    ctx.t("labs.bin.trace.lpm", "linear probability model"),
                    "negative", theme=ctx.theme, dash="dash")
        P.add_curve(fig, grid, 1 / (1 + np.exp(-np.clip(G @ logit["beta"], -35, 35))),
                    ctx.t("labs.bin.trace.logit", "logit"), "primary", theme=ctx.theme,
                    width=3.0)
        P.add_curve(fig, grid, stats.norm.cdf(G @ probit["beta"]),
                    ctx.t("labs.bin.trace.probit", "probit"), "secondary",
                    theme=ctx.theme, dash="dot", width=2.6)
        P.add_hline(fig, 0.0, "", "baseline", theme=ctx.theme, dash="dot")
        P.add_hline(fig, 1.0, "", "baseline", theme=ctx.theme, dash="dot")
        binned = self._binned_means(x, y)
        P.add_points(fig, binned[0], binned[1],
                     ctx.t("labs.bin.trace.binned", "binned observed frequency"),
                     "truth", theme=ctx.theme, size=10)
        P.add_legend_note(fig, ctx.t(
            "labs.bin.legend_curves",
            "Logit and probit are nearly indistinguishable over the range where data are "
            "dense. The straight line is the one that eventually walks out of [0, 1].",
        ), theme=ctx.theme)
        return fig

    @staticmethod
    def _binned_means(x, y, bins: int = 12):
        edges = np.quantile(x, np.linspace(0, 1, bins + 1))
        edges = np.unique(edges)
        idx = np.clip(np.digitize(x, edges[1:-1]), 0, len(edges) - 2)
        centres, means = [], []
        for b in range(len(edges) - 1):
            mask = idx == b
            if mask.sum() > 3:
                centres.append(float(np.mean(x[mask])))
                means.append(float(np.mean(y[mask])))
        return np.asarray(centres), np.asarray(means)

    def _marginal_figure(self, ctx, x, logit, probit, lpm):
        grid = np.linspace(float(x.min()), float(x.max()), 300)
        G = np.column_stack([np.ones(grid.size), grid])
        idx_l = np.clip(G @ logit["beta"], -35, 35)
        pl = 1 / (1 + np.exp(-idx_l))
        me_logit = pl * (1 - pl) * logit["beta"][1]
        me_probit = stats.norm.pdf(G @ probit["beta"]) * probit["beta"][1]
        fig = ctx.figure(
            "labs.bin.figure.marginal",
            xaxis_title=ctx.t("labs.common.axis.x"),
            yaxis_title=ctx.t("labs.bin.axis.marginal",
                              "Marginal effect: dP(y=1)/dx"),
            height=370,
        )
        P.add_curve(fig, grid, me_logit,
                    ctx.t("labs.bin.trace.me_logit", "logit marginal effect"),
                    "primary", theme=ctx.theme)
        P.add_curve(fig, grid, me_probit,
                    ctx.t("labs.bin.trace.me_probit", "probit marginal effect"),
                    "secondary", theme=ctx.theme, dash="dot")
        P.add_hline(fig, lpm.coef("x"),
                    ctx.t("labs.bin.trace.lpm_constant",
                          "LPM: one constant effect everywhere"),
                    "negative", theme=ctx.theme, dash="dash")
        P.add_hline(fig, float(logit["ame"][1]),
                    ctx.t("labs.bin.trace.ame", "logit average marginal effect"),
                    "truth", theme=ctx.theme, dash="dot")
        P.add_legend_note(fig, ctx.t(
            "labs.bin.legend_marginal",
            "The effect of x depends on where you stand: largest near a predicted "
            "probability of one half, vanishing at the extremes. The LPM replaces this "
            "curve with a single number, which is often close to its average.",
        ), theme=ctx.theme)
        return fig

    def _lpm_figure(self, ctx, x, lpm):
        order = np.argsort(x)
        fitted = lpm.fitted_values[order]
        fig = ctx.figure(
            "labs.bin.figure.lpm",
            xaxis_title=ctx.t("labs.common.axis.x"),
            yaxis_title=ctx.t("labs.bin.axis.fitted", "LPM fitted probability"),
            height=350,
        )
        P.add_curve(fig, x[order], fitted,
                    ctx.t("labs.bin.trace.lpm_fitted", "LPM fitted values"),
                    "negative", theme=ctx.theme)
        bad = (fitted < 0) | (fitted > 1)
        if bad.any():
            P.add_points(fig, x[order][bad], fitted[bad],
                         ctx.t("labs.bin.trace.impossible",
                               "impossible probabilities"),
                         "warning", theme=ctx.theme, size=7)
        P.add_hline(fig, 0.0, "0", "baseline", theme=ctx.theme)
        P.add_hline(fig, 1.0, "1", "baseline", theme=ctx.theme)
        var = np.clip(fitted, 0, 1) * (1 - np.clip(fitted, 0, 1))
        P.add_curve(fig, x[order], var,
                    ctx.t("labs.bin.trace.lpm_variance",
                          "implied error variance p(1-p)"),
                    "warning", theme=ctx.theme, dash="dot")
        P.add_legend_note(fig, ctx.t(
            "labs.bin.legend_lpm",
            "Two structural problems in one picture: predictions leave [0, 1], and the error "
            "variance is a function of x by construction, so the LPM is always "
            "heteroskedastic.",
        ), theme=ctx.theme)
        return fig

    def _sampling_figure(self, ctx, sim):
        fig = ctx.figure(
            "labs.bin.figure.sampling",
            xaxis_title=ctx.t("labs.bin.axis.effect", "Estimated average marginal effect"),
            yaxis_title=ctx.t("labs.common.axis.density"),
            height=360,
        )
        for key, role, label in (
            ("lpm", "negative", ctx.t("labs.bin.trace.lpm", "linear probability model")),
            ("ame_logit", "primary", ctx.t("labs.bin.trace.ame_logit_short",
                                           "logit AME")),
            ("ame_probit", "secondary", ctx.t("labs.bin.trace.ame_probit_short",
                                              "probit AME")),
        ):
            vals = sim[key][np.isfinite(sim[key])]
            if vals.size:
                P.add_histogram(fig, vals, label, role, theme=ctx.theme, nbins=45,
                                opacity=0.45)
        P.add_legend_note(fig, ctx.t(
            "labs.bin.legend_sampling",
            "The three histograms usually sit almost on top of each other. That is the "
            "practical reason the linear probability model survives in applied work despite "
            "its theoretical flaws.",
        ) + "  " + ctx.t("labs.common.note.simulation"), theme=ctx.theme)
        return fig

    def _animation(self, ctx, p, n, seed):
        go = P.require_plotly()
        betas = np.linspace(0.0, 3.0, 16)
        grid = np.linspace(-4 * float(p["x_spread"]), 4 * float(p["x_spread"]), 300)
        G = np.column_stack([np.ones(grid.size), grid])
        frames, steps = [], []
        for i, b in enumerate(betas):
            q = dict(p)
            q["beta1"] = float(b)
            x, y = self._generate(q, n, seed)
            X = np.column_stack([np.ones(n), x])
            lg = fit_binary(y, X, "logit")
            lp = LM.ols(y, X, names=("const", "x"))
            curve = 1 / (1 + np.exp(-np.clip(G @ lg["beta"], -35, 35)))
            frames.append(go.Frame(name=f"{b:.2f}", data=[
                go.Scatter(x=grid, y=curve),
                go.Scatter(x=grid, y=G @ lp.coefficients),
            ]))
            steps.append(AnimationStep(
                id=f"b_{i}", frame=i,
                title=ctx.t("labs.bin.anim.title", "index coefficient = {b}", b=fmt(b, 2)),
                what_you_see=ctx.t("labs.bin.anim.see",
                                   "The fitted logit probability curve and the linear "
                                   "probability line for the same data."),
                what_changed=ctx.t("labs.bin.anim.changed",
                                   "The true effect of x on the index moved to {b}.",
                                   b=fmt(b, 2)),
                why=ctx.t("labs.bin.anim.why",
                          "A larger index coefficient steepens the S-curve, concentrating "
                          "the transition from 'almost never' to 'almost always' into a "
                          "narrower range of x."),
                interpretation=ctx.t("labs.bin.anim.interpret",
                                     "Logit AME = {a}, LPM slope = {l}, and {k} LPM "
                                     "predictions now fall outside [0, 1].",
                                     a=fmt(float(lg["ame"][1]), 4),
                                     l=fmt(lp.coef("x"), 4),
                                     k=int(np.sum((lp.fitted_values < 0) |
                                                  (lp.fitted_values > 1)))),
                conclusion=ctx.t("labs.bin.anim.conclude",
                                 "The two summaries agree on the average effect long after "
                                 "the straight line has stopped being a valid probability."),
                warning=ctx.t("labs.bin.anim.warn",
                              "The index coefficient is not the effect on the probability. "
                              "Only the marginal effect is interpretable on that scale."),
                math="P(y=1|x) = F(b0 + b1 x);  dP/dx = f(b0 + b1 x) * b1",
                outputs={"beta1": round(float(b), 3),
                         "logit_ame": round(float(lg["ame"][1]), 5),
                         "lpm_slope": round(lp.coef("x"), 5)},
                highlighted=("logit_curve", "lpm_line"),
            ))
        fig = ctx.figure(
            "labs.bin.figure.animation",
            xaxis_title=ctx.t("labs.common.axis.x"),
            yaxis_title=ctx.t("labs.bin.axis.probability", "P(y = 1 | x)"),
            height=390,
        )
        fig.add_trace(go.Scatter(x=grid, y=np.full_like(grid, 0.5), mode="lines",
                                 line={"color": ctx.color("primary"), "width": 3.0},
                                 name=ctx.t("labs.bin.trace.logit", "logit")))
        fig.add_trace(go.Scatter(x=grid, y=np.full_like(grid, 0.5), mode="lines",
                                 line={"color": ctx.color("negative"), "dash": "dash"},
                                 name=ctx.t("labs.bin.trace.lpm",
                                            "linear probability model")))
        P.add_hline(fig, 0.0, "", "baseline", theme=ctx.theme, dash="dot")
        P.add_hline(fig, 1.0, "", "baseline", theme=ctx.theme, dash="dot")
        fig.update_yaxes(range=[-0.35, 1.35])
        build_frames(fig, frames, duration=440, reduced_motion=ctx.reduced_motion,
                     slider_label=ctx.t("labs.bin.slider", "effect size"))
        return animation(
            "steepening_curve", fig, steps,
            purpose=ctx.t("labs.bin.anim.purpose",
                          "Show where the linear approximation holds and where it breaks."),
            summary=ctx.t(
                "labs.bin.anim.summary",
                "A binary outcome forces the fitted probability into [0, 1], which a "
                "straight line cannot respect. Logit and probit solve that by bending the "
                "line - at the price that the coefficient is no longer the effect, and only "
                "the marginal effect can be read directly."),
            evidence=EvidenceType.NUMERICAL_DEMONSTRATION,
        )


LAB = BinaryChoiceLab(SPEC)
